---
title: "On the role of surrogates in the efficient estimation of treatment effects with limited outcome data"
output: pdf_document
date: "2024-12-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Including Plots

```{r}
library(R.matlab)
library(splitTools)
library(ranger)
library(doParallel)
library(foreach)
library(gbm)
library(glmnet)
library(lemon)
library(mgcv)
library(np)
library(tidyverse)
library(haven)
select = dplyr::select
```

```{r}
# 读取模拟的 Riverside GAIN 数据
# 使用 haven 包中的 read_dta 函数来读取 .dta 文件
raw_data <- read_dta("simulated Riverside GAIN data.dta")

# 检查数据列名是否符合预期
head(raw_data)
```

```{r}
# 创建 data 数据框架
# 确保 emp1 到 emp36 是数值类型
raw_data <- raw_data %>% mutate(across(starts_with("emp"), as.numeric))
data <- data.frame(raw_data)

# 计算 emp 变量从 1 到 36 的累计均值
data$cum_emp_1 <- data$emp1
for (i in 2:36) {
  data[[paste0("cum_emp_", i)]] <- rowMeans(df[paste0("emp", 1:i)], na.rm = TRUE)
}

# 计算平均就业率
treatment_avg <- colMeans(data[data$treatment == 1,
                               paste0("emp", 1:36)], na.rm = TRUE) * 100
control_avg <- colMeans(data[data$treatment == 0,
                             paste0("emp", 1:36)], na.rm = TRUE) * 100

head(data)
```

```{r}
library(R.matlab)
library(splitTools)
library(ranger)
library(doParallel)
library(foreach)
library(gbm)
library(glmnet)
library(lemon)
library(mgcv)
library(np)
library(tidyverse)
select = dplyr::select


#####################
#   ATE Estimation  #
#####################
est_truth <- function(data, nuisances){
  # difference-in-mean ATE estimator using the full data 
  Y = data$Y; e = data$e
  mean(Y[e == 1]) - mean(Y[e==0])
}
est_dr_X_label <- function(data, nuisances){
  # doubly robust ATE estimator using only labelled data ("DR + Labelled" in Figure 1)
  data_temp = data[data$R == 1, ]
  mu_x1 = nuisances$mu_x1[data$R == 1]
  mu_x0 = nuisances$mu_x0[data$R == 1]
  ehat = nuisances$ehat
  Y = data_temp$Y; e = data_temp$e
  
  temp = mu_x1 - mu_x0 +
    (Y - mu_x1) * e/ehat -
    (Y - mu_x0) * (1 - e)/(1 - ehat)
  mean(temp)
}
est_dr_X_full <- function(data, nuisances){
  # doubly robust ATE estimator using both labelled and unlabelled data ("DR + s=0" in Figure 1)
  mu_x1 = nuisances$mu_x1
  mu_x0 = nuisances$mu_x0
  ehat = nuisances$ehat
  rhat = nuisances$rhat
  Y = data$Y; e = data$e; R = data$R
  
  temp = mu_x1 - mu_x0 + 
    (Y - mu_x1) * (e * R)/(ehat * rhat) - 
    (Y - mu_x0) * ((1 - e) * R)/((1 - ehat) * rhat)
  mean(temp)
}
est_XS_proposal <- function(data, nuisances){
  # our proposed estimator ("Proposal" in Figure 1)
  mu_x1 = nuisances$mu_x1
  mu_x0 = nuisances$mu_x0
  ehat = nuisances$ehat
  rhat = nuisances$rhat
  Y = data$Y; e = data$e; R = data$R
  
  estimates = rep(NA, length(nuisances$mu_xs1))
  for (i in seq_along(nuisances$mu_xs1)){
    mu_xs1 = nuisances$mu_xs1[[i]]
    mu_xs0 = nuisances$mu_xs0[[i]]
    temp = mu_x1 - mu_x0 + 
      (Y - mu_xs1) * (e * R)/(ehat *rhat) - 
      (Y - mu_xs0) * ((1 - e) * R)/((1 - ehat) *rhat) +
      (mu_xs1 - mu_x1) * e/ehat -
      (mu_xs0 - mu_x0) * (1 - e)/(1 - ehat)
    estimates[i] = mean(temp)
  }
  names(estimates) = paste0("propDR_", names(nuisances$mu_xs))
  estimates
}
est_XS_athey <- function(data, nuisances){
  # the surrogate index estimator based on regression imputation in 
  # Athey et al. [2019] (denoted as "SIndex REG" in Figure 1)
  
  ehat = nuisances$ehat
  rhat = nuisances$rhat
  Y = data$Y; e = data$e; R = data$R
  estimates = rep(NA, length(nuisances$mu_xs))
  for (i in seq_along(nuisances$mu_xs)){
    mu_xs = nuisances$mu_xs[[i]]
    estimates[i] = mean(mu_xs[e==1]) - mean(mu_xs[e==0])
  }
  names(estimates) = paste0("athey_", names(nuisances$mu_xs))
  estimates
}

########################
#  Nuisance Estimation #
########################
# compute_nuisances_rf 函数
compute_nuisances_rf <- function(data, folds, x_list, s_length_list, obs_ratio){
  ehat = sum(data$e)/nrow(data) 
  rhat = sum(data$R)/nrow(data)   

  # 初始化 mu_x1 和 mu_x0
  mu_x1 = rep(NA, nrow(data))
  mu_x0 = rep(NA, nrow(data))
  
  if(length(x_list) > 0){
    # 如果有协变量，使用 ranger 进行建模
    form_x = as.formula(paste("Y ~", paste(x_list, collapse = "+")))
    for (fold_idx in 1:length(folds)){
      fold=folds[[fold_idx]]
      data_train = data[fold, ]
      data_eval =  data[-fold, ]
      data_train$e = factor(data_train$e, levels = c(1, 0))
      data_eval$e = factor(data_train$e, levels = c(1, 0))
      
      learner_x1 = ranger(formula = form_x,
                          data = data_train[(data_train$R==1)&(data_train$e==1), ])
      learner_x0 = ranger(formula = form_x,
                          data = data_train[(data_train$R==1)&(data_train$e==0), ])
      mu_x1[-fold] = predict(learner_x1, data = data_eval)$predictions
      mu_x0[-fold] = predict(learner_x0, data = data_eval)$predictions
    }
  } else {
    # 如果没有协变量，直接使用分组均值
    mu_x1[] = mean(data$Y[data$R == 1 & data$e == 1], na.rm = TRUE)
    mu_x0[] = mean(data$Y[data$R == 1 & data$e == 0], na.rm = TRUE)
  }
  
  # 处理 mu_xs1, mu_xs0, mu_xs
  mu_xs1 = vector("list", length=length(s_length_list))
  mu_xs0 = vector("list", length=length(s_length_list))
  mu_xs = vector("list", length=length(s_length_list))
  for (j in seq_along(s_length_list)){
    xs_list = c(x_list, paste0("cum_emp_", 1:s_length_list[j]))
    
    if(length(xs_list) > 0){
      form_xs = as.formula(paste("Y ~", paste(xs_list, collapse = "+")))
      mu_xs1[[j]] = rep(NA, nrow(data))
      mu_xs0[[j]] = rep(NA, nrow(data))
      mu_xs[[j]] = rep(NA, nrow(data))
      for (fold_idx in 1:length(folds)){
        fold=folds[[fold_idx]]
        data_train = data[fold, ]
        data_eval =  data[-fold, ]
        
        learner_xs1 = ranger(formula = form_xs,
                             data = data_train[(data_train$R==1)&(data_train$e==1), ])
        learner_xs0 = ranger(formula = form_xs,
                             data = data_train[(data_train$R==1)&(data_train$e==0), ])
        learner_xs = ranger(formula = form_xs,
                            data = data_train[(data_train$R==1), ])
        mu_xs1[[j]][-fold] = predict(learner_xs1, data = data_eval)$predictions
        mu_xs0[[j]][-fold] = predict(learner_xs0, data = data_eval)$predictions
        mu_xs[[j]][-fold] = predict(learner_xs, data = data_eval)$predictions
      }
    } else {
      # 如果 xs_list 为空，直接使用分组均值
      mu_xs1[[j]] = rep(mean(data$Y[data$R == 1 & data$e == 1], na.rm = TRUE), nrow(data))
      mu_xs0[[j]] = rep(mean(data$Y[data$R == 1 & data$e == 0], na.rm = TRUE), nrow(data))
      mu_xs[[j]] = rep(mean(data$Y[data$R == 1], na.rm = TRUE), nrow(data))
    }
  }
  names(mu_xs1) = paste0("s", s_length_list)
  names(mu_xs0) = paste0("s", s_length_list)
  names(mu_xs) = paste0("s", s_length_list)

  list(mu_xs1 = mu_xs1, mu_xs0 = mu_xs0, mu_xs = mu_xs,
       mu_x1 = mu_x1, mu_x0 = mu_x0,
       ehat = ehat, rhat = rhat)
}


########################
#      Evaluation      #
########################
compute_S_power <- function(data, nuisances){
  # calculate the cross-validated predictiveness of surrogates according to our 
  # nuisance estimates of \tilde{mu}(t, x, s) and mu(t, x)
  total1 = mean((data$Y[data$e == 1] - nuisances$mu_x1[data$e == 1])^2)
  total0 = mean((data$Y[data$e == 0] - nuisances$mu_x0[data$e == 0])^2)
  sub1 = rep(NA, length(nuisances$mu_xs1)); sub0 = rep(NA, length(nuisances$mu_xs0))
  for (i in 1:length(nuisances$mu_xs1)){
    sub1[i] = mean((data$Y[data$e == 1] - nuisances$mu_xs1[[i]][data$e == 1])^2)
    sub0[i] = mean((data$Y[data$e == 0] - nuisances$mu_xs0[[i]][data$e == 0])^2)
  }
  R1 = 1 - sub1/total1
  R0 = 1 - sub0/total0
  list(R1 = R1, R0 = R0)
}
convert_res_to_df_obs_ratio <- function(result, obs_ratio_list, nuisance){
  # convert the .rds results to a data frame
  temp = vector("list", length=length(obs_ratio_list))
  for (i in seq_along(obs_ratio_list)){
    temp_inner = transpose(result)[[i]]
    temp[[i]] = as.data.frame(
      do.call(
        rbind, lapply(temp_inner, function(x) x[["est"]][[nuisance]])))
    temp[[i]] = temp[[i]] %>% pivot_longer(
      everything(), names_to = "method", values_to = "estimate") %>% 
      mutate(obs_ratio = paste0("r = ", obs_ratio_list[i]))
  }
  do.call(rbind, temp)
}

modify_notations <- function(res_df, s_length_list, s_list_plot_error){
  # modify a few notations 
  res_df$S = 0
  ind = grepl("_s", res_df$method) 
  res_df$S[ind] = sapply(str_split(res_df$method[ind], "_s"), function(x) as.numeric(x[2]))
  res_df$type = NA
  res_df$type[grepl("label", res_df$method)] = "Labelled"
  res_df$type[grepl("full", res_df$method)] = "s=0"
  res_df$type[grepl("truth", res_df$method)] = "truth"
  res_df$type[is.na(res_df$type)] = paste0("s=", res_df$S[is.na(res_df$type)])
  res_df = res_df %>% filter(type %in% c("Labelled", "s=0", paste0("s=", s_list_plot_error)))
  res_df$type = factor(res_df$type, levels = c("Labelled", "s=0", paste0("s=", s_list_plot_error)))
  res_df$method = sapply(str_split(res_df$method, "_"), function(x) x[1])
  res_df
}

```

```{r}
rep_num = 120
core_num = 60
s_length_list = 4*(1:9)
obs_ratio_list = c(0.1, 0.3, 0.5)

# list of covariates 
x_list = c()  

est_functions_no_S = list(est_truth, est_dr_X_label, est_dr_X_full)
# baseline ATE estimators without using surrogates  
#   est_truth: the oracle difference-in-mean ATE estimator based on the 
#              whole dataset, whose result is viewed as the "truth" for 
#              calculating the bias of other estimators 
#  est_dr_X_label: doubly robust ATE estimator using only labelled data 
#                   ("DR + Labelled" in Figure 1)
#   est_dr_X_full: doubly robust ATE estimator using both labelled and unlabelled 
#                  data, but ignore the surrogates ("DR + s=0" in Figure 1)
est_functions_S = list(est_XS_proposal, est_XS_athey)
# ATE estimators that use the surrogate information 
#   est_XS_proposal: our proposed estimator ("Proposal" in Figure 1)
#   est_XS_athey: the surrogate index estimator based on regression imputation in 
#       Athey et al. [2019] (denoted as "SIndex REG" in Figure 1)
#    the semiparametrically efficient surrogate index estimator proposed in 

compute_nuisance_functions = c("grf" = compute_nuisances_rf)
# list of estimators used to estimate nuisances: 
#   random forests (grf), gradient boosting (xgboost), lasso (glmnet)
#   here the names grf, xgboost and glmnet are used to keep consistent

experiment_obs_ratio_once <- function(
    obs_ratio, s_length_list, data, x_list,
    compute_nuisance_functions, est_functions_no_S, est_functions_S){
  
  n1 = sum(data$e == 1)
  n0 = sum(data$e == 0)
  ind = partition(data$e, p = c(train = obs_ratio, test = 1-obs_ratio)) 
    # subsample 1-obs_ratio of the data to have missing labels 
  ind_label = ind$train
  ind_miss = ind$test
  data$R = 1
  data$R[ind_miss] = 0
  
  data$RE_type = 4
  data$RE_type[(data$R==0)&(data$e==0)] = 1
  data$RE_type[(data$R==0)&(data$e==1)] = 2
  data$RE_type[(data$R==1)&(data$e==0)] = 3
  folds = create_folds(data$RE_type, k = 5)   
    # split the data into 5 even folds for cross-fitting; the splitting is 
    # stratified on the missingness and the treatment indicators  
  
  est = vector("list", length(compute_nuisance_functions))
  Rsquare = vector("list", length(compute_nuisance_functions))
  for (i in seq_along(compute_nuisance_functions)){
    nuisances = compute_nuisance_functions[[i]](data, folds, x_list, s_length_list, obs_ratio)
      # fit the nuisances using the ith method (i is grf, xgboost, or lasso)
    est_res_no_S = sapply(est_functions_no_S, function(f) f(data, nuisances))
    names(est_res_no_S) = c("truth", "DR_label", "DR_X_full")
      # estimate ATE using estimators that do not need surrogate observations 
    est_res_S = lapply(est_functions_S, function(f) f(data, nuisances))
    est_res_S = unlist(est_res_S)
      # estimate ATE using estimators that need surrogate observations 
    est[[i]] = c(est_res_no_S, est_res_S)
    Rsquare[[i]] = compute_S_power(data, nuisances)
      # calculate the cross-validated predictiveness of the surrogates 
  }
  names(est) = names(compute_nuisance_functions)
  names(Rsquare) = names(compute_nuisance_functions)
  list(est = est, Rsquare = Rsquare)
}

set.seed(2024)

data$Y = data$cum_emp_36
data$e = data$treatment

time1 = proc.time()
cl <- makeCluster(core_num)
registerDoParallel(cl)
result = foreach(i = 1:rep_num, .packages = c("tidyverse", "splitTools", "ranger", "gbm", "glmnet", "np", "mgcv")) %dopar% {
  cat(paste("The", i, "th repetition \n"))
  res_temp = vector("list", length = length(obs_ratio_list))
  for (i in seq_along(obs_ratio_list)){
    res_temp[[i]] =  tryCatch({
      experiment_obs_ratio_once(obs_ratio_list[i],
                                s_length_list, data, x_list, compute_nuisance_functions,
                                est_functions_no_S, est_functions_S)
    },  error = function(e) return(paste0("'", e, "'")))
  }
  res_temp
}
stopCluster(cl)
time2 = proc.time()
time2 - time1

saveRDS(result, paste0("result_", city,
                       "_rep", rep_num,
                       ".rds"))
```

```{r}
plot_errors_new <- function(result, nuisance, s_list_plot_error){
  # result = result[sapply(result, length) > 1]
  res_df = convert_res_to_df_obs_ratio(result, obs_ratio_list, nuisance) 
  truth = res_df$estimate[res_df$method == "truth"][1]
  res_df = res_df %>% modify_notations(s_length_list, s_list_plot_error)
  res_df[res_df$method == "athey", "method"] = "SIndex_REG"
  
  temp = res_df %>% 
    filter(!(method %in% c("truth"))) %>% filter(type != "S=36") 
  temp$method[temp$method == "propDR"] = "Proposal"
  
  temp = temp %>% group_by(method, type, obs_ratio) %>%  
    summarise(mean = mean(estimate), std = sd(estimate)) %>% 
    mutate(bias = abs(mean - truth)) %>% 
    mutate(rmse = sqrt(bias^2 + std^2))
  plts = vector("list", length = 3)
  plts[[1]] = temp %>% ggplot(aes(x=type, y=bias, fill=method)) + 
    geom_col(position = "dodge", color = "black") +
    facet_wrap(~obs_ratio) + 
    ylab("Bias")
  plts[[2]] = temp %>% ggplot(aes(x=type, y=std, fill=method)) + 
    geom_col(position = "dodge", color = "black") +
    facet_wrap(~obs_ratio) + ylab("Standard Error")
  plts
}


###################
#    Riverside
###################
city = "river"

s_list_plot_error = c(8, 16, 24, 32)
obs_ratio_list = c(0.1, 0.3, 0.5)
s_length_list = 4*(1:9)

print(paste0("result_", city, "_rep", rep_num, ".rds"))
result = readRDS(paste0("result_", city, "_rep", rep_num, ".rds"))

nuisance = "grf"
plts = plot_errors_new(result, nuisance, s_list_plot_error)
grid_arrange_shared_legend(plts[[1]], plts[[2]], nrow = 2, ncol = 1)

```
